command: [
  "python",
  "app.py"
]
env:
- name: "DATABRICKS_WAREHOUSE_ID"
  valueFrom: "sql-warehouse"
- name: "LLM_ENDPOINT"
  valueFrom: "serving-endpoint"
- name: "DASHBOARD_URL"
  valueFrom: "dashboard-url"
# - name: "DATABRICKS_TOKEN"
#   valueFrom: "DATABRICKS_TOKEN"